Color.create! name: "fuschia", html_color_code: "#FF00FF"  
Color.create! name: "green", html_color_code: "#00FF00"
Color.create! name: "purple", html_color_code: "#6666FF"
Color.create! name: "yellow", html_color_code: "#FFFF00"  
Vehicle.create! name: "airplane", image_filename: "plane.png"
Vehicle.create! name: "bicycle", image_filename: "bike.png"
Vehicle.create! name: "bus", image_filename: "bus.png"
Vehicle.create! name: "car", image_filename: "car.png"